In [3]:
## start learning numpy 

In [4]:
import numpy as np
import time

In [5]:
array_2d = np.array([[1,2,3],[9,8,7]])
print("2d array: ",array_2d)


2d array:  [[1 2 3]
 [9 8 7]]


In [6]:
start = time.time()

lst = [i*2 for i in range(100000)]
print("\n list time : " ,time.time() - start)


 list time :  0.008505105972290039


In [7]:
arr = np.arange(100000)*2
print("\n array time : ", time.time()-start)


 array time :  0.022771120071411133


In [9]:
arrl = np.array([1,2,3,4,5,6])
print("this is and list which convert into array : ",arrl)
print(type(arrl))

this is and list which convert into array :  [1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [13]:
arr_3d= np.array([[1,2],[1,3],[2,3]])
print("this is 3d array: ",arr_3d)
print(arr_3d.size)
print(arr_3d.shape)
print(arr_3d.dtype)

this is 3d array:  [[1 2]
 [1 3]
 [2 3]]
6
(3, 2)
int64


In [15]:
zero_arr = np.zeros((3,3))
print("this is 3 by 3 matrices\n", zero_arr)

this is 3 by 3 matrices
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr_one = np.ones((4,4))
print("this is matrix of one : \n",arr_one)

this is matrix of one : 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
arr_rndm = np.random.rand(3,3)
print(arr_rndm)

[[0.6242306  0.56873969 0.15198806]
 [0.81899634 0.77085854 0.79046415]
 [0.8932983  0.56876391 0.69726575]]


In [31]:
print(np.random.randint(1,9,(3,3)))

[[6 6 7]
 [8 3 3]
 [1 4 8]]


In [37]:
arr_2d = np.random.randint(5,20,(3,4))
print("task done \n ",arr_2d)
print(arr_2d.shape,"\n",arr_2d.size)



task done 
  [[10 12  5 10]
 [ 9 11 17 11]
 [ 6 15 14  8]]
(3, 4) 
 12


In [38]:
#array operations 

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,3])

print(arr1+arr2)
print(arr1-arr2)
print(arr1/arr2)
print(arr1*arr2)
print(arr1//arr2)
print(arr1**arr2)

[ 7  9 11 13  8]
[-5 -5 -5 -5  2]
[0.16666667 0.28571429 0.375      0.44444444 1.66666667]
[ 6 14 24 36 15]
[0 0 0 0 1]
[     1    128   6561 262144    125]


In [43]:
# some built-in functions for mathematics
arrb1 = np.array([10, 20, 30])
print(np.sum(arrb1))
print(np.max(arrb1))
print(np.min(arrb1))
print(np.std(arrb1))
print(np.median(arrb1))


60
30
10
8.16496580927726
20.0


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A + B)  # Element-wise addition
print(A - B)  # Element-wise subtraction
print(A * B)  # Element-wise multiplication
print(np.dot(A, B))  # Matrix multiplication
print(np.linalg.inv(A))  # Inverse of matrix in this linalg means linear Algebra 
